#!/usr/bin/env python3
"""
Verifier: transpiles the TfNSW Gold-layer Databricks Delta DDL down to a
SQLite-loadable dialect and builds an in-memory catalog to prove:
  - every table parses,
  - every PK/FK/UK constraint is syntactically valid,
  - every FK references an existing table + key.
Prints a PASS/FAIL report.
"""
import re, sqlite3, sys, os

DDL_FILES = [
    os.path.join('gold', '01_customer_patronage.sql'),
    os.path.join('gold', '02_network_service_performance.sql'),
    os.path.join('gold', '03_asset_maintenance.sql'),
]

def strip_comments(sql):
    """Remove -- line comments and /* */ block comments, preserving string literals approx."""
    # Remove -- line comments (not inside single-quoted strings - rare here)
    sql = re.sub(r"--[^\n]*", "", sql)
    # Remove /* */ block comments
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.S)
    return sql

def transpile(ddl):
    """Databricks-Delta-DDL -> SQLite-compatible DDL (structural checks only)."""
    ddl = strip_comments(ddl)
    ddl = ddl.replace('CREATE OR REPLACE TABLE', 'CREATE TABLE')
    ddl = re.sub(r"GENERATED BY DEFAULT AS IDENTITY\s*", "", ddl)
    # Strip inline column COMMENT 'xxx' AND trailing table-level COMMENT 'xxx'
    ddl = re.sub(r"COMMENT\s+'[^']*'", "", ddl)
    # Split into per-statement blocks on CREATE TABLE, and ensure exactly one
    # terminating ';' at the end of each block (only after the closing ')' of the
    # table body - not on arbitrary inner ')').
    parts = re.split(r"(?=CREATE TABLE)", ddl)
    rebuilt = []
    for part in parts:
        if not part.strip():
            continue
        part = part.rstrip("\n; \t")
        # If it still looks like a table body without a terminator, add one.
        if not part.rstrip().endswith(";"):
            part += ";"
        rebuilt.append(part)
    ddl = "\n".join(rebuilt)
    # Databricks types -> SQLite
    ddl = re.sub(r"\bSTRING\b", "TEXT", ddl)
    ddl = re.sub(r"\bDOUBLE\b", "REAL", ddl)
    ddl = re.sub(r"\bBOOLEAN\b", "INTEGER", ddl)
    ddl = re.sub(r"\bTIMESTAMP\b", "TEXT", ddl)
    ddl = re.sub(r"\bTIME\b", "TEXT", ddl)
    ddl = re.sub(r"\bDATE\b", "TEXT", ddl)
    ddl = re.sub(r"\bDECIMAL\([^)]*\)", "REAL", ddl)  # simplify decimals for parse check
    ddl = re.sub(r"\bBIGINT\b", "INTEGER", ddl)
    ddl = re.sub(r"\bINT\b", "INTEGER", ddl)
    ddl = re.sub(r"\bSMALLINT\b", "INTEGER", ddl)
    ddl = re.sub(r"\bgold\.", "", ddl)   # strip schema qualifier
    return ddl

def main():
    combined = ""
    for f in DDL_FILES:
        with open(f, encoding="utf-8") as fh:
            combined += transpile(fh.read()) + "\n"

    conn = sqlite3.connect(":memory:")
    errors = []
    statements = [s.strip() for s in combined.split(";") if s.strip() and s.strip() not in (")", "", "USE")]
    for stmt in statements:
        if stmt.upper().startswith("USE "):
            continue
        if stmt.strip(")").strip() == "":
            continue
        try:
            conn.execute(stmt)
        except sqlite3.Error as e:
            errors.append(f"{stmt[:70]!r} -> {e}")

    cur = conn.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    tables = [r[0] for r in cur.fetchall()]

    print(f"Tables built successfully in-memory: {len(tables)}")
    for t in tables:
        print(f"   - {t}")

    if errors:
        print("\n=== DDL PARSE ERRORS ===")
        for e in errors:
            print("   ", e)
    else:
        print("\n=== ALL DDL STATEMENTS PARSED OK ===")

    # FK referential integrity
    print("\n=== FOREIGN KEY REFERENTIAL CHECKS ===")
    fk_fail = 0
    for t in tables:
        row = conn.execute('SELECT sql FROM sqlite_master WHERE type="table" AND name=?', (t,)).fetchone()
        sql = row[0]
        for m in re.finditer(r"REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)", sql, re.I):
            ref_tab, ref_col = m.group(1), m.group(2)
            if ref_tab not in tables:
                print(f"  [FAIL] {t} -> missing table {ref_tab}"); fk_fail += 1
                continue
            tdef = conn.execute('SELECT sql FROM sqlite_master WHERE name=?', (ref_tab,)).fetchone()[0]
            if re.search(rf"\b{re.escape(ref_col)}\b", tdef) is None:
                print(f"  [FAIL] {t} -> {ref_tab}.{ref_col} column not found"); fk_fail += 1
    if fk_fail == 0:
        print("  All FK targets resolved; no dangling references.")
    else:
        print(f"  {fk_fail} FK issue(s) to review.")

    sys.exit(0 if not errors and fk_fail == 0 else 2)

if __name__ == "__main__":
    main()