-- =====================================================================
--  TfNSW GOLD LAYER — Model 01: Customer Patronage & Journey
--  (Dimensional / Kimball star-schema style)
--  Target: Databricks Delta / Snowflake Gold schema
--
--  BUSINESS PROCESS: Fare collection, journey/patronage capture,
--  "single view of customer" & voice-of-customer analytics.
--
--  GRAIN:
--    fact_trip   = one tap-off-closed trip (a single leg of travel
--                  from one tap-on to one tap-off), per card/per run.
--    fact_journey = one completed customer journey (a collection of
--                   up to 8 trips made within the transfer window).
--
--  IMPORTANT TfNSW DOMAIN FACTS:
--   - A TRIP  = single unit of travel, tap-on -> tap-off.
--   - A JOURNEY = 1..=8 trips linked by the <=1h transfer rule
--     (Manly ferry 130min tap-on window). Trip Advantage fuses
--     same-mode consecutive trips into a single tariff.
--   - Opal cards: Adult, Child/Youth, Senior/Pensioner, Concession,
--     Employee, School. Contactless debit/credit paid as Adult.
--   - Fares are distance-based per mode group (metro/train,
--     bus/light rail, ferry) with peak/off-peak, daily/weekly/Sunday
--     caps, transfer discounts, and default (no tap-off) fares.
--
--  SCD: dim_customer and dim_card are SCD Type 2 (historical
--  entitlements & registration state preserved).
-- =====================================================================
USE SCHEMA gold;

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_time
-- Shared across all gold marts. Row per gregorian minute (or hour for
-- coarse grains). Sharded time hierarchy for punctuality analysis.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_time (
    time_sk                  BIGINT          COMMENT 'Surrogate key: YYYYMMDDHH24MISS',
    calendar_date            DATE            NOT NULL,
    time_of_day              TIME            NOT NULL,
    hour_of_day              SMALLINT        NOT NULL,
    minute_of_day            SMALLINT        NOT NULL,
    -- Fare-period classification per TfNSW peak rules (widened from Jul 2020)
    peak_period_flag         BOOLEAN         NOT NULL,
    fare_period              STRING          COMMENT 'PEAK | OFF_PEAK | WEEKDAY | SATURDAY | SUNDAY',
    is_weekday               BOOLEAN         NOT NULL,
    is_friday_sat_sun        BOOLEAN         NOT NULL COMMENT 'Fri->Sun off-peak since Oct 2023',
    calendar_week_start_date DATE            NOT NULL,
    calendar_month           STRING          NOT NULL,
    financial_quarter        STRING          NOT NULL COMMENT 'e.g. FY2026-Q1 (Jul)',
    financial_year           STRING          NOT NULL,
    iso_week                 STRING          NOT NULL,
    CONSTRAINT pk_dim_time PRIMARY KEY (time_sk)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_mode
-- The five fare modes + point-to-point / other.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_mode (
    mode_sk              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    mode_code            STRING        NOT NULL,   -- 'METRO','TRAIN','BUS','FERRY','LRT',
                                                   -- 'COACH','P2P','ROAD','OTHER'
    mode_name            STRING        NOT NULL,
    fare_mode_group      STRING        NOT NULL COMMENT 'metro/train | bus/lightrail | ferry | other',
    dsg_contract_mode    BOOLEAN        COMMENT 'True if operated under transport service contract',
    brand                STRING        COMMENT 'Sydney Metro|Sydney Trains|NSW TrainLink|Sydney Buses|Sydney Ferries|Sydney Light Rail|Newcastle Transport',
    active_flag          BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_mode PRIMARY KEY (mode_sk),
    CONSTRAINT uk_dim_mode_code UNIQUE (mode_code)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_operator
-- Operator that actually runs the vehicle/run (TfNSW brands are not
-- always the operating entity - operations are contracted out).
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_operator (
    operator_sk          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    operator_code        STRING        NOT NULL,
    operator_name        STRING        NOT NULL,
    owner_category       STRING        COMMENT 'ST_PUBLIC | PRIVATE_CONTRACT | SOC',
    parent_entity        STRING        COMMENT 'e.g. TAHE, Transport Service of NSW, Transdev',
    contract_region      STRING        COMMENT 'Greater Sydney | Outer Metro | Regional NSW | Newcastle | Interstate',
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_operator PRIMARY KEY (operator_sk),
    CONSTRAINT uk_dim_operator_code UNIQUE (operator_code, scd_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_stop_location
-- One row per geographic stop/station/wharf/light-rail stop.
-- Rich geospatial + accessibility attributes for placemaking (SAT).
-- Grain = one physical stop location.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_stop_location (
    location_sk          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    stop_id              STRING        NOT NULL,        -- GTFS / opendata stop id
    stop_name            STRING        NOT NULL,
    stop_type            STRING        COMMENT 'TRAIN_STATION | METRO_STATION | BUS_STOP | FERRY_WHARF | LIGHT_RAIL_STOP | COACH_STOP',
    platform_number      STRING,
    latitude             DOUBLE,
    longitude            DOUBLE,
    zone_id              STRING        COMMENT 'Opal distance-based fare zone',
    suburb               STRING,
    lga_code             STRING        COMMENT 'Local Government Area code',
    region               STRING        COMMENT 'Greater Sydney | Blue Mountains | Central Coast | Wollongong | Hunter | Illawarra | Southern Highlands | Regional NSW',
    accessible_flag      BOOLEAN       COMMENT 'Step-free / lift access present',
    bike_parking_flag    BOOLEAN,
    park_and_ride_flag   BOOLEAN,
    geom_wkt            STRING        COMMENT 'PostGIS/WKT geometry (optional)',
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_stop_location PRIMARY KEY (location_sk),
    CONSTRAINT uk_dim_stop UNIQUE (stop_id, scd_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_service
-- A scheduled service (train line / bus route / ferry route / light-rail
-- line) that passengers can board. Dual-nature: also references the
-- GTFS route for network modelling (see Model 02).
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_service (
    service_sk           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    service_code         STRING        NOT NULL,        -- e.g. 'T1','T2','M1','B-Line','N68','F1','L2','L3','L4'
    service_name         STRING        NOT NULL,
    mode_fk              BIGINT        NOT NULL,
    operator_fk          BIGINT        NOT NULL,
    transport_line_flag  BOOLEAN       COMMENT 'True if part of a named corridor (e.g. T1 North Shore)',
    intercity_flag       BOOLEAN       COMMENT 'True for NSW TrainLink intercity',
    contract_route_flag  BOOLEAN       COMMENT 'True if a contracted bus route',
    effective_start_date DATE,
    effective_end_date   DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_service PRIMARY KEY (service_sk),
    CONSTRAINT fk_service_mode FOREIGN KEY (mode_fk) REFERENCES dim_mode (mode_sk),
    CONSTRAINT fk_service_operator FOREIGN KEY (operator_fk) REFERENCES dim_operator (operator_sk),
    CONSTRAINT uk_dim_service_code UNIQUE (service_code, effective_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_customer_party
-- Registered customer / contact point. SCD Type 2.
-- Privacy: classified as RESTRICTED (personal data) under TfNSW
-- data governance. Only consent-based enrichment.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_customer_party (
    customer_sk          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    customer_key         STRING        NOT NULL,        -- opaque enterprise customer id (pseudonymised)
    title                STRING,
    first_name           STRING        COMMENT 'PII - encrypted at rest',
    last_name            STRING        COMMENT 'PII',
    date_of_birth        DATE,
    gender               STRING        COMMENT 'allowed values per TfNSW survey standard',
    postcode             STRING,
    lga_code             STRING,
    email                STRING        COMMENT 'PII',
    mobile_phone         STRING        COMMENT 'PII',
    marketing_consent_flag BOOLEAN,
    accessibility_need   STRING        COMMENT 'e.g. wheelchair, vision-impaired (Vision Impaired Travel Pass)',
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_customer PRIMARY KEY (customer_sk),
    CONSTRAINT uk_dim_customer_key UNIQUE (customer_key, scd_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_card
-- The fare instrument (physical Opal card / digital Opal / contactless
-- PAN token). SCD Type 2. Card type drives most fare rules.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_card (
    card_sk              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    card_token           STRING        NOT NULL,        -- hashed card number (PAN never stored raw)
    card_type            STRING        NOT NULL COMMENT 'ADULT | CHILD_YOUTH | SENIOR_PENSIONER | CONCESSION | EMPLOYEE | SCHOOL | CONTACTLESS | DIGITAL_OPAL | FREETRAVEL',
    payment_channel      STRING        COMMENT 'OPAL_CARD | OPAL_TRAVEL_APP | CONTACTLESS_DEBIT | CONTACTLESS_CREDIT | MOBILE_WALLET',
    load_mechanism       STRING        COMMENT 'AUTO_TOP_UP | MANUAL | RETAIL | MACHINE',
    auto_top_up_flag     BOOLEAN       DEFAULT FALSE,
    auto_top_up_amount   DECIMAL(7,2)  COMMENT 'default $10 threshold',
    maximum_balance      DECIMAL(7,2)  COMMENT 'Adult/Senior $250, others $150',
    issue_date           DATE,
    expiry_date          DATE          COMMENT '14-year credit expiry for adult cards',
    card_status          STRING        COMMENT 'ACTIVE | BLOCKED | REPORTED_LOST | EXPIRED | REFUNDED',
    customer_fk          BIGINT        COMMENT 'nullable - unregistered cards have no customer',
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_card PRIMARY KEY (card_sk),
    CONSTRAINT fk_card_customer FOREIGN KEY (customer_fk) REFERENCES dim_customer_party (customer_sk),
    CONSTRAINT uk_dim_card_token UNIQUE (card_token, scd_end_date)
);

-- ---------------------------------------------------------------------
-- BRIDGE: bridge_card_concession
-- Many-to-many between card and concession entitlement. A customer may
-- hold multiple eligible entitlements; eligibility must be re-verified
-- (e.g. student enrolment consent via the institution).
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE bridge_card_concession (
    bridge_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    card_fk              BIGINT        NOT NULL,
    concession_code      STRING        NOT NULL COMMENT 'STUDENT | APPRENTICE | TRAINEE | JOBSEEKER | SENIOR | PENSIONER | DISABILITY | SCHOOL_STUDENT',
    entitlement_source   STRING        COMMENT 'Institution | Services Australia | DVA | TfNSW',
    verification_status  STRING        COMMENT 'VERIFIED | PENDING | EXPIRED | REVOKED',
    entitlement_start_date DATE,
    entitlement_end_date DATE,
    verified_date        DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_bridge_card_concession PRIMARY KEY (bridge_id),
    CONSTRAINT fk_bcc_card FOREIGN KEY (card_fk) REFERENCES dim_card (card_sk)
);

-- =======================================================================
--  FACT: fact_trip
--  GRAIN: one closed trip (tap-on -> tap-off) for one fare instrument
--  on one service run. Additivity: fare amount is fully additive (net of
--  caps yet to be applied); distance additive; duration additive (seconds).
-- =======================================================================
CREATE OR REPLACE TABLE fact_trip (
    trip_id              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    card_sk              BIGINT        NOT NULL,
    customer_sk          BIGINT,                        -- resolved at Silver
    mode_sk              BIGINT         NOT NULL,
    operator_sk          BIGINT         NOT NULL,
    service_sk           BIGINT,
    origin_location_sk   BIGINT         NOT NULL,
    destination_location_sk BIGINT      NOT NULL,
    tap_on_time_sk       BIGINT         NOT NULL,        -- dim_time
    tap_off_time_sk      BIGINT,
    trip_date            DATE           NOT NULL,
    tap_on_time          TIMESTAMP      NOT NULL,
    tap_off_time         TIMESTAMP,
    trip_sequence_in_journey SMALLINT   COMMENT '1..8 position within the journey',
    -- Core measures
    distance_km          DECIMAL(8,2),
    trip_duration_sec    INT,
    fare_amount_aud      DECIMAL(7,2)   COMMENT 'gross fare before caps/weekly reward',
    default_fare_flag    BOOLEAN        COMMENT 'true if charged default (no tap-off/ max journey time)',
    peak_period_flag     BOOLEAN,
    transfer_discount_aud DECIMAL(6,2)  COMMENT '$2 adult / $1 other mode-transfer discount',
    trip_advantage_fused_flag BOOLEAN   COMMENT 'true if merged into prior same-mode trip tariff',
    -- Provenance / audit (gold tracks silver -> bronze lineage)
    record_source        STRING         COMMENT 'Opal back-office | contactless acquirer | on-demand operator',
    load_datetime        TIMESTAMP      NOT NULL,
    CONSTRAINT pk_fact_trip PRIMARY KEY (trip_id),
    CONSTRAINT fk_trip_card FOREIGN KEY (card_sk) REFERENCES dim_card (card_sk),
    CONSTRAINT fk_trip_customer FOREIGN KEY (customer_sk) REFERENCES dim_customer_party (customer_sk),
    CONSTRAINT fk_trip_mode FOREIGN KEY (mode_sk) REFERENCES dim_mode (mode_sk),
    CONSTRAINT fk_trip_operator FOREIGN KEY (operator_sk) REFERENCES dim_operator (operator_sk),
    CONSTRAINT fk_trip_service FOREIGN KEY (service_sk) REFERENCES dim_service (service_sk),
    CONSTRAINT fk_trip_origin FOREIGN KEY (origin_location_sk) REFERENCES dim_stop_location (location_sk),
    CONSTRAINT fk_trip_dest FOREIGN KEY (destination_location_sk) REFERENCES dim_stop_location (location_sk),
    CONSTRAINT fk_trip_ton FOREIGN KEY (tap_on_time_sk) REFERENCES dim_time (time_sk),
    CONSTRAINT fk_trip_toff FOREIGN KEY (tap_off_time_sk) REFERENCES dim_time (time_sk)
)
COMMENT 'Grain: one closed trip per fare instrument. Fully additive on fare/duration/distance.';
-- Physical: partition by trip_date; ZORDER by (card_sk, mode_sk)

-- =======================================================================
--  FACT: fact_journey
--  GRAIN: one completed customer journey (a collection of 1..=8 trips
--  linked by transfer rules). Enables cross-modal journey analysis,
--  interchange optimisation, and MaaS single-view-of-customer.
-- =======================================================================
CREATE OR REPLACE TABLE fact_journey (
    journey_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    card_sk              BIGINT         NOT NULL,
    customer_sk          BIGINT,
    first_trip_tap_on    TIMESTAMP      NOT NULL,
    last_trip_tap_off    TIMESTAMP,
    journey_date         DATE           NOT NULL,
    journey_start_time_sk BIGINT        NOT NULL,
    journey_end_time_sk  BIGINT,
    origin_location_sk   BIGINT         NOT NULL,
    destination_location_sk BIGINT      NOT NULL,
    -- Measures
    total_trips          SMALLINT       NOT NULL COMMENT '1..8',
    modes_used           STRING         COMMENT 'comma-delimited fare mode groups',
    journey_duration_sec INT,
    total_fare_aud       DECIMAL(8,2),
    transfer_count       SMALLINT,
    interchange_optimality_score DECIMAL(5,2) COMMENT 'planning/insight metric',
    -- Audit
    load_datetime        TIMESTAMP      NOT NULL,
    CONSTRAINT pk_fact_journey PRIMARY KEY (journey_id),
    CONSTRAINT fk_journey_card FOREIGN KEY (card_sk) REFERENCES dim_card (card_sk),
    CONSTRAINT fk_journey_customer FOREIGN KEY (customer_sk) REFERENCES dim_customer_party (customer_sk),
    CONSTRAINT fk_journey_origin FOREIGN KEY (origin_location_sk) REFERENCES dim_stop_location (location_sk),
    CONSTRAINT fk_journey_dest FOREIGN KEY (destination_location_sk) REFERENCES dim_stop_location (location_sk)
)
COMMENT 'Grain: one completed journey (1..=8 trips). Semi-additive: reuse total_trips, modes_used.';
-- Partition by journey_date.

-- ---------------------------------------------------------------------
--  AGGREGATE MART (optional, for performance): agg_patronage_daily
--  GRAIN: service x origin x destination x date x period. Pre-built for
--  on-time reporting dashboards and the Strategy's near-real-time
--  insights (pull from fact_trip / fact_journey).
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE agg_patronage_daily (
    service_sk           BIGINT        NOT NULL,
    mode_sk              BIGINT        NOT NULL,
    origin_location_sk   BIGINT        NOT NULL,
    destination_location_sk BIGINT     NOT NULL,
    trip_date            DATE          NOT NULL,
    peak_period_flag     BOOLEAN       NOT NULL,
    trip_count           BIGINT        NOT NULL,
    passenger_km         DECIMAL(14,2) NOT NULL,
    total_fare_aud       DECIMAL(14,2) NOT NULL,
    -- synthetic grain + audit
    CONSTRAINT pk_agg_patronage PRIMARY KEY (service_sk, origin_location_sk, destination_location_sk, trip_date, peak_period_flag)
)
COMMENT 'Pre-aggregated patronage for dashboards - non-normalised, compact grain (service x od x day x period).';