-- =====================================================================
--  TfNSW GOLD LAYER — Model 02: Network & Service Performance
--  (Dimensional, GTFS/TransXChange-inspired reference backbone + OTP)
--  Target: Databricks Delta / Snowflake Gold schema
--
--  BUSINESS PROCESS: Timetabling & planning; service operations &
--  real-time; interchange & accessibility.
--
--  GRAIN:
--    fact_service_run   = one scheduled run of a service on one
--                         calendar day (train/bus/ferry/LRT trip).
--    fact_stop_dwell    = one planned/actual stop visit for a run.
--
--  WHY GTFS-BASED: TfNSW publishes complete GTFS (and TransXChange)
--  timetables for all operators. The Gold network reference model is a
--  curated, time-variant projection of those feeds into conformed
--  dimensions, so downstream marts (patronage, OTP, accessibility) share
--  one network truth. SCD on operator/route/stop assignments.
--
--  OTP (On-Time Performance) definition used here follows NSW rail/bus
--  conventions: a run is 'on time' within a tolerance window and is
--  only measured at designated timing points.
-- =====================================================================
USE SCHEMA gold;

-- Reuse conformed dim_time, dim_mode, dim_operator, dim_stop_location,
-- dim_service from model 01 where the grains align (shared conformed
-- dimensions - the hallmark of a Gold layer). Re-declared here for a
-- self-contained example where needed.

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_route
-- GTFS 'routes.txt' analogue: a named line/route (T1, B-Line, F1, L2...).
-- 1 route belongs to 1 operator & 1 mode. Route geometric corridor.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_route (
    route_sk             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    route_id             STRING        NOT NULL,          -- GTFS route_id
    agency_id            STRING        NOT NULL,          -- GTFS agency_id
    route_short_name     STRING        COMMENT 'e.g. T1, 333, F1',
    route_long_name      STRING        COMMENT 'e.g. North Shore & Western Line',
    route_type           STRING        COMMENT 'GTFS route_type: TRAIN | METRO | BUS | FERRY | TRAM/LRT | COACH',
    mode_fk              BIGINT        NOT NULL,
    operator_fk          BIGINT        NOT NULL,
    start_location_sk    BIGINT,
    end_location_sk      BIGINT,
    color                STRING,
    route_length_km      DECIMAL(8,2),
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_route PRIMARY KEY (route_sk),
    CONSTRAINT fk_route_mode FOREIGN KEY (mode_fk) REFERENCES gold.dim_mode (mode_sk),
    CONSTRAINT fk_route_operator FOREIGN KEY (operator_fk) REFERENCES gold.dim_operator (operator_sk),
    CONSTRAINT uk_dim_route UNIQUE (route_id, agency_id, scd_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_trip_pattern
-- GTFS 'trips.txt' analogue: a specific scheduled journey of a route,
-- defined by a trip_headsign and a service calender pattern. It is the
-- bridge between a route (corridor) and the individual runs.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_trip_pattern (
    trip_pattern_sk      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    route_sk             BIGINT        NOT NULL,
    trip_id              STRING        NOT NULL,          -- GTFS trip_id
    shape_id             STRING,                          -- GTFS shape_id (geometry)
    headsign             STRING,
    direction_id         SMALLINT      COMMENT '0 outbound, 1 inbound (GTFS convention)',
    wheelchair_accessible SMALLINT     COMMENT '1 yes / 2 no',
    bikes_allowed        SMALLINT      COMMENT '1 yes / 2 no',
    service_id           STRING        COMMENT 'GTFS calendar service pattern id',
    typical_weekday_flag BOOLEAN,
    typical_saturday_flag BOOLEAN,
    typical_sunday_flag  BOOLEAN,
    CONSTRAINT pk_dim_trip_pattern PRIMARY KEY (trip_pattern_sk),
    CONSTRAINT fk_tp_route FOREIGN KEY (route_sk) REFERENCES dim_route (route_sk),
    CONSTRAINT uk_dim_trip_pattern UNIQUE (trip_id)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_calendar_service
-- GTFS 'calendar.txt' / 'calendar_dates.txt' analogue: which days a
-- given service pattern operates (incl. exceptions: public holidays,
-- trackwork replacements, special events).
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_calendar_service (
    calendar_sk          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    service_id           STRING        NOT NULL,
    service_date         DATE          NOT NULL,
    operating_flag       BOOLEAN       NOT NULL COMMENT 'scheduled to operate this day',
    exception_type       STRING        COMMENT 'NONE | PUBLIC_HOLIDAY | TRACKWORK | DISRUPTION | ADDED_SERVICE',
    substitution_service_fk BIGINT     COMMENT 'if trackwork, the replacement service used',
    source               STRING        COMMENT 'GTFS calendar | calendar_dates',
    CONSTRAINT pk_dim_calendar PRIMARY KEY (calendar_sk),
    CONSTRAINT uk_calendar_service_date UNIQUE (service_id, service_date)
);

-- ---------------------------------------------------------------------
-- BRIDGE: bridge_route_stop
-- M:N between route and stop location; also captures the ordered,
-- distance-based stop geometry used for fare zones + accessibility.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE bridge_route_stop (
    bridge_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    route_sk             BIGINT        NOT NULL,
    location_sk          BIGINT        NOT NULL,
    stop_sequence        INT           NOT NULL COMMENT '0-based GTFS stop_sequence',
    distance_from_start  DECIMAL(8,2)  COMMENT 'shape_dist_traveled (km)',
    is_timing_point_flag BOOLEAN       COMMENT 'OTP is measured at these',
    CONSTRAINT pk_bridge_route_stop PRIMARY KEY (bridge_id),
    CONSTRAINT fk_brs_route FOREIGN KEY (route_sk) REFERENCES dim_route (route_sk),
    CONSTRAINT fk_brs_loc FOREIGN KEY (location_sk) REFERENCES gold.dim_stop_location (location_sk),
    CONSTRAINT uk_brs UNIQUE (route_sk, location_sk, stop_sequence)
);

-- =======================================================================
--  FACT: fact_service_run
--  GRAIN: one scheduled run (trip instance) of a trip pattern on a
--  calendar day. This is the SCD-preserved 'scheduled vs actual' truth.
-- =======================================================================
CREATE OR REPLACE TABLE fact_service_run (
    service_run_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    trip_pattern_sk      BIGINT        NOT NULL,
    route_sk             BIGINT        NOT NULL,
    operator_sk          BIGINT        NOT NULL,
    mode_sk              BIGINT        NOT NULL,
    calendar_sk          BIGINT        NOT NULL,
    scheduled_start_time_sk BIGINT     NOT NULL,
    scheduled_end_time_sk   BIGINT,
    vehicle_asset_fk     BIGINT        COMMENT 'assigned rolling stock / bus (nullable: dynamic allocation)',  
    scheduled_start_datetime TIMESTAMP NOT NULL,
    scheduled_end_datetime   TIMESTAMP,
    actual_start_datetime    TIMESTAMP,
    actual_end_datetime      TIMESTAMP,
    -- OTP measures (Tolerance-based: rail is typically 'on-time' within
    -- a set minutes threshold at timing points)
    on_time_flag         BOOLEAN,
    early_minutes        INT,
    late_minutes         INT,
    cancelled_flag       BOOLEAN       DEFAULT FALSE,
    short_turn_flag      BOOLEAN       COMMENT 'terminated before full run',
    wait_time_avg_sec    INT           COMMENT 'average excess wait for NUW headways (metro/bus)',
    dwell_total_sec      INT,
    run_distance_km      DECIMAL(8,2),
    -- Audit
    record_source        STRING,
    load_datetime        TIMESTAMP     NOT NULL,
    CONSTRAINT pk_fact_service_run PRIMARY KEY (service_run_id),
    CONSTRAINT fk_run_tp FOREIGN KEY (trip_pattern_sk) REFERENCES dim_trip_pattern (trip_pattern_sk),
    CONSTRAINT fk_run_route FOREIGN KEY (route_sk) REFERENCES dim_route (route_sk),
    CONSTRAINT fk_run_calendar FOREIGN KEY (calendar_sk) REFERENCES dim_calendar_service (calendar_sk)
)
COMMENT 'Grain: one scheduled run per day per trip_pattern. Semi-additive: use on_time_flag, late_minutes.';
-- Partition by scheduled_start_date-derived date.

-- =======================================================================
--  FACT: fact_stop_dwell
--  GRAIN: one stop-visit event for one service run. Enables dwell-time
--  analysis, interchange optimisation, and real-time arrival forecasting.
-- =======================================================================
CREATE OR REPLACE TABLE fact_stop_dwell (
    dwell_id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    service_run_fk       BIGINT        NOT NULL,
    location_sk          BIGINT        NOT NULL,
    stop_sequence        INT           NOT NULL,
    scheduled_arrival    TIMESTAMP,
    scheduled_departure  TIMESTAMP,
    actual_arrival       TIMESTAMP,
    actual_departure     TIMESTAMP,
    dwell_time_sec       INT           COMMENT 'actual_departure - actual_arrival',
    departure_delay_sec  INT           COMMENT 'actual_departure - scheduled_departure',
    alighting_count      INT           COMMENT 'at-stop boarding/alighting (survey/AVL-derived)',
    boarding_count       INT,
    load_from_previous   INT           COMMENT 'estimated load on arrival (supports crowding)',
    is_timing_point      BOOLEAN       NOT NULL,
    CONSTRAINT pk_fact_stop_dwell PRIMARY KEY (dwell_id),
    CONSTRAINT fk_dwell_run FOREIGN KEY (service_run_fk) REFERENCES fact_service_run (service_run_id),
    CONSTRAINT fk_dwell_loc FOREIGN KEY (location_sk) REFERENCES gold.dim_stop_location (location_sk)
)
COMMENT 'Grain: one stop visit for one run. dwell_time_sec & counts additive; flags semi-additive.';
-- Partition by date(scheduled_arrival).

-- -----------------------------------------------------------------------
--  AGGREGATE MART: agg_otp_daily
--  GRAIN: route x date x period -> on-time performance % & reliability
--  metrics. Feeds the reliability reporting and real-time OTP dashboards.
-- -----------------------------------------------------------------------
CREATE OR REPLACE TABLE agg_otp_daily (
    route_sk             BIGINT        NOT NULL,
    mode_sk              BIGINT        NOT NULL,
    service_date         DATE          NOT NULL,
    peak_period_flag     BOOLEAN       NOT NULL,
    scheduled_run_count  INT           NOT NULL,
    actual_run_count     INT           NOT NULL,
    on_time_run_count    INT           NOT NULL,
    on_time_percent      DECIMAL(6,3)  NOT NULL,
    avg_late_minutes     DECIMAL(6,2),
    cancelled_run_count  INT,
    system_avg_on_time_percent DECIMAL(6,3),
    CONSTRAINT pk_agg_otp PRIMARY KEY (route_sk, service_date, peak_period_flag)
)
COMMENT 'Pre-built Gold OTP KPI mart - compact non-normalised aggregate.';

-- Create index support for the hot query path (route + date + timing point)
-- (Delta: clustering key; Snowflake: clustering on service_date, route_sk)