-- =====================================================================
--  TfNSW GOLD LAYER — Model 03: Asset Register & Predictive Maintenance
--  (Corporate 3NF-normalised model; Gold analytical asset mart)
--  Target: Databricks Delta / Snowflake Gold schema
--
--  BUSINESS PROCESS: Asset ownership (TAHE + TfNSW fleet), condition
--  monitoring, maintenance planning & execution, energy/net-zero
--  lifecycle, and the Strategy's 'predictive asset maintenance' & Net
--  Zero analytics pillar. Note: Sydney Trains is among top-5 electricity
--  users in NSW (1.3% of total); Net Zero for electricity achieved 2021.
--
--  GRAIN:
--    fact_asset_operation  = one operational/health event per asset
--                             (trip segment, energy reading, fault flag).
--    fact_work_order       = one work order (maintenance/defect) against
--                             an asset or component.
--
--  ASSET TAXONOMY: rolling stock (trains, buses, ferries, light-rail),
--  track & civil, stations/stops, signals & systems, power, road assets,
--  maritime aids. TAHE owns rail assets; TfNSW fleet vehicles ~10,432.
--  Assets have a hierarchy (asset -> parent assembly -> component).
-- =====================================================================
USE SCHEMA gold;

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_asset_class / dim_asset
-- The asset hierarchy. dim_asset_class categorises the asset type and
-- drives maintenance regimes & condition thresholds.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_asset_class (
    asset_class_sk       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    asset_class_code     STRING        NOT NULL,   -- 'ROLLING_STOCK','STATION','TRACK','SIGNAL',
                                                  -- 'POWER_SUPPLY','FERRY_VESSEL','ROAD_ASSET',
                                                  -- 'INTERCHANGE','LIGHT_RAIL'
    asset_class_name     STRING        NOT NULL,
    parent_class_fk      BIGINT,                    -- for hierarchy
    maintenance_regime   STRING        COMMENT 'TIME_BASED | CONDITION_BASED | RUNNING_KM | PREDICTIVE',
    replacement_cost_aud DECIMAL(18,2),
    CONSTRAINT pk_dim_asset_class PRIMARY KEY (asset_class_sk),
    CONSTRAINT fk_asset_class_parent FOREIGN KEY (parent_class_fk) REFERENCES dim_asset_class (asset_class_sk),
    CONSTRAINT uk_asset_class_code UNIQUE (asset_class_code)
);

CREATE OR REPLACE TABLE dim_asset (
    asset_sk             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    asset_tag            STRING        NOT NULL,        -- TAHE / fleet asset id
    asset_class_fk       BIGINT        NOT NULL,
    asset_name           STRING,
    serial_number        STRING,
    manufacturer         STRING        COMMENT 'e.g. hitachi, Powin, Cubic (maintainer)',
    manufacture_date     DATE,
    in_service_date      DATE,
    current_operator_fk  BIGINT        COMMENT 'which transport agency currently operates/holds',
    owning_entity        STRING        COMMENT 'TAHE | TfNSW | RTC | private lessee',
    location_fk          BIGINT        COMMENT 'base / depot / home station',
    asset_status         STRING        COMMENT 'IN_SERVICE | MAINTENANCE | STORED | DEFECT | SOLD',
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_asset PRIMARY KEY (asset_sk),
    CONSTRAINT fk_asset_class FOREIGN KEY (asset_class_fk) REFERENCES dim_asset_class (asset_class_sk),
    CONSTRAINT uk_dim_asset_tag UNIQUE (asset_tag, scd_end_date)
);

-- ---------------------------------------------------------------------
-- CONFORMED DIMENSION: dim_component
-- Maintainable sub-assembly of an asset (e.g. a train's traction motor,
-- wheelset, door actuator, HVAC unit). Predictive maintenance operates at
-- this level.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE dim_component (
    component_sk         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    component_code       STRING        NOT NULL,
    component_name       STRING        NOT NULL,
    asset_class_fk       BIGINT        NOT NULL,
    criticality          STRING        COMMENT 'CRITICAL | HIGH | MEDIUM | LOW (safety criticality)',
    mean_time_to_fail_hr DECIMAL(10,2) COMMENT 'MTTF benchmark',
    smart_sensor_flag    BOOLEAN       COMMENT 'True if instrumented (IoT condition monitoring)',
    CONSTRAINT pk_dim_component PRIMARY KEY (component_sk),
    CONSTRAINT fk_component_class FOREIGN KEY (asset_class_fk) REFERENCES dim_asset_class (asset_class_sk)
);

-- Component<->Asset is M:N in reality (swapped parts) - resolve via
-- bridge_asset_component with instalment history.
CREATE OR REPLACE TABLE bridge_asset_component (
    bridge_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    asset_fk             BIGINT        NOT NULL,
    component_fk         BIGINT        NOT NULL,
    fitted_date          DATE          NOT NULL,
    removed_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    accumulated_usage_km DECIMAL(10,2),
    CONSTRAINT pk_bridge_asset_component PRIMARY KEY (bridge_id),
    CONSTRAINT fk_bac_asset FOREIGN KEY (asset_fk) REFERENCES dim_asset (asset_sk),
    CONSTRAINT fk_bac_component FOREIGN KEY (component_fk) REFERENCES dim_component (component_sk)
);

-- =======================================================================
--  FACT: fact_asset_operation
--  GRAIN: one operational/health/energy event for one asset-component
--  (e.g. a run segment, an hourly energy meter read, a fault flag). High
--  volume; the Strategy's predictive-analytics enabler input.
-- =======================================================================
CREATE OR REPLACE TABLE fact_asset_operation (
    operation_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    asset_fk             BIGINT        NOT NULL,
    component_fk         BIGINT,
    time_sk              BIGINT        NOT NULL,
    event_datetime       TIMESTAMP     NOT NULL,
    event_type           STRING        COMMENT 'ENERGY_READING | RUN_SEGMENT | FAULT_FLAG | CONDITION_SAMPLE | POSITION',
    operation_location_fk BIGINT       COMMENT 'where the asset was (service run / depot)',
    -- Measures
    energy_kwh           DECIMAL(12,2) COMMENT 'electricity consumed (Sydney Trains is 1.3% of NSW use)',
    usage_km             DECIMAL(10,2),
    usage_hours          DECIMAL(8,2),
    speed_kmh            DECIMAL(6,2),
    temperature_c        DECIMAL(5,2)   COMMENT 'IoT condition sample',
    vibration_ms2        DECIMAL(6,3),
    fault_code           STRING,
    severity             STRING         COMMENT 'INFO | WARNING | CRITICAL',
    -- Audit
    record_source        STRING         COMMENT 'SCADA | telematics | AVL | energy meter | IoT sensor',
    load_datetime        TIMESTAMP      NOT NULL,
    CONSTRAINT pk_fact_asset_operation PRIMARY KEY (operation_id),
    CONSTRAINT fk_ao_asset FOREIGN KEY (asset_fk) REFERENCES dim_asset (asset_sk),
    CONSTRAINT fk_ao_component FOREIGN KEY (component_fk) REFERENCES dim_component (component_sk)
)
COMMENT 'Grain: one asset-operational/health event. energy_kwh additive; temperature/vibration semi-additive.';
-- Partition by event_date; ZORDER by (asset_fk, event_type).

-- =======================================================================
--  FACT: fact_work_order
--  GRAIN: one work order (maintenance / defect / inspection) raised
--  against an asset or component. Foundation for predictive maintenance:
--  correlate condition-sensitive history with failures to forecast.
-- =======================================================================
CREATE OR REPLACE TABLE fact_work_order (
    work_order_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    asset_fk             BIGINT        NOT NULL,
    component_fk         BIGINT,
    location_fk          BIGINT        COMMENT 'depot / maintenance facility',
    wo_type              STRING        COMMENT 'BREAKDOWN | PLANNED_MAINTENANCE | CONDITION_BASED | INSPECTION | MODIFICATION',
    wo_status            STRING        COMMENT 'RAISED | SCHEDULED | IN_PROGRESS | COMPLETE | CANCELLED',
    priority             STRING        COMMENT 'P1 | P2 | P3 (safety first)',
    raised_datetime      TIMESTAMP     NOT NULL,
    scheduled_datetime   TIMESTAMP,
    completed_datetime   TIMESTAMP,
    -- Measures
    labour_hours         DECIMAL(8,2),
    material_cost_aud    DECIMAL(12,2),
    total_cost_aud       DECIMAL(12,2),
    asset_downtime_hours DECIMAL(8,2),
    km_at_work_order     DECIMAL(10,2) COMMENT 'asset odometer when raised',
    inspection_finding   STRING        COMMENT 'text finding (may be structured severity)',
    -- Root cause / reliability
    failure_mode         STRING        COMMENT 'e.g. door actuator failure, wheel flange wear',
    -- Audit
    record_source        STRING,
    load_datetime        TIMESTAMP     NOT NULL,
    CONSTRAINT pk_fact_work_order PRIMARY KEY (work_order_id),
    CONSTRAINT fk_wo_asset FOREIGN KEY (asset_fk) REFERENCES dim_asset (asset_sk),
    CONSTRAINT fk_wo_component FOREIGN KEY (component_fk) REFERENCES dim_component (component_sk)
)
COMMENT 'Grain: one work order per asset/component. Cost & downtime additive; status semi-additive.';
-- Partition by raised date.

-- =======================================================================
--  CONFORMED DIMENSION: dim_project   (funds infrastructure the assets)
--  Ties the Strategy's capital project portfolio (Sydney Metro West,
--  WSA, Parramatta LRT, Digital Systems) to assets delivered/upgraded.
-- =======================================================================
CREATE OR REPLACE TABLE dim_project (
    project_sk           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    project_code         STRING        NOT NULL,
    project_name         STRING        NOT NULL,
    project_type         STRING        COMMENT 'RAPID_TRANSIT | LIGHT_RAIL | ROADS | ROLLING_STOCK | DIGITAL_SYSTEMS | ACCESSIBILITY',
    program              STRING        COMMENT 'e.g. Sydney Metro, Digital Systems Program, Transport Access Program',
    status               STRING        COMMENT 'PLANNED | UNDERWAY | COMPLETE | CANCELLED',
    expected_completion  DATE,
    scd_start_date       DATE,
    scd_end_date         DATE,
    current_flag         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_dim_project PRIMARY KEY (project_sk),
    CONSTRAINT uk_dim_project_code UNIQUE (project_code)
);

-- Project <-> Asset M:N bridge
CREATE OR REPLACE TABLE bridge_project_asset (
    bridge_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    project_fk           BIGINT        NOT NULL,
    asset_fk             BIGINT        NOT NULL,
    works_type           STRING        COMMENT 'BUILD | UPGRADE | REPLACE | MAINTAIN',
    CONSTRAINT pk_bridge_project_asset PRIMARY KEY (bridge_id),
    CONSTRAINT fk_bpa_project FOREIGN KEY (project_fk) REFERENCES dim_project (project_sk),
    CONSTRAINT fk_bpa_asset FOREIGN KEY (asset_fk) REFERENCES dim_asset (asset_sk)
)

-- AGGREGATE MART: agg_asset_reliability_daily
-- GRAIN: asset class x component x date -> reliability KPIs for the
-- predictive-maintenance dashboard.
CREATE OR REPLACE TABLE agg_asset_reliability_daily (
    asset_class_fk       BIGINT        NOT NULL,
    component_fk         BIGINT        NOT NULL,
    event_date           DATE          NOT NULL,
    total_operations     INT           NOT NULL,
    fault_count          INT           NOT NULL,
    critical_fault_count INT           NOT NULL,
    total_energy_kwh     DECIMAL(16,2),
    reliability_percent  DECIMAL(6,3),
    CONSTRAINT pk_agg_asset_rel PRIMARY KEY (asset_class_fk, component_fk, event_date)
)
COMMENT 'Asset reliability KPI mart - aggregate for reporting.';